spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/json_datasets
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: false
server:
  port: 8080
